name: Build (npm + maven) + Report

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: aggregator-webui/package-lock.json

    - name: Update npm dependencies
      run: |
        cd aggregator-webui
        npm install

    - name: Build jsx
      run: |
        cd aggregator-webui
        npm run build

    - uses: actions/upload-artifact@v4
      with:
        name: frontend-artifact
        path: aggregator-webui/dist

  build-backend:
    needs: build-frontend

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Fetch frontend build result
      uses: actions/download-artifact@v4
      with:
        name: frontend-artifact
        path: aggregator-webui/dist

    - name: Prepare build environment
      run: mvn -B dependency:resolve-plugins dependency:resolve

    - name: Build aggregator-core
      run: mvn -B -pl aggregator-core clean package install

    - name: Copy aggregator-webui build artifacts for embedding
      run: |
        rm -r aggregator-app/src/main/resources/assets/webapp
        mkdir aggregator-app/src/main/resources/assets/webapp
        cp -R aggregator-webui/dist/lib/. aggregator-app/src/main/resources/assets/webapp/

    - name: Build aggregator-app
      run: mvn -B -pl aggregator-app clean package

    - name: Prepare build artifact for packaging
      run: |
        mkdir -p staging/target
        cp aggregator-app/aggregator.yml staging/
        cp aggregator-app/target/aggregator-app-*.jar staging/target/

    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging

  mvn-site-report:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Use Java 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Generate report
      run: |
        mvn -ntp clean site
        mv target/site report

    - uses: actions/upload-artifact@v4
      with:
        name: Report
        path: report
